<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Fitness admin</title>
  <link rel="stylesheet" href="./css/vertical-layout-light/style.css">
 
  <!-- endinject -->
  <link rel="shortcut icon" href="./images/logo-black2.png" />
</head>
  <style>
    input[type="email"]:focus,input[type="password"]:focus  {
      border-color: black;
      outline: none;
    }
  </style>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-5 mx-auto">
            <div class="auth-form-light text-left py-4 px-4 px-sm-5 rounded rounded-5 shadow-sm">
              <div class="d-flex flex-row justify-content-center align-items-end">
                <img src="./images/logo-black2.png" alt="logo" style="width: 130px;">
              </div>
              <form class="pt-3">
                <div class="form-group">
                  <input type="email" class="form-control"  id="InputEmail" placeholder="Username">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control" id="InputPassword" placeholder="Password">
                </div>
                <div class="mt-3">
                  <a class="btn btn-dark font-weight-medium btn-block" href="./pages/dashboard.php">SIGN IN</a>
                </div>
                <div class="my-3 d-flex justify-content-end align-items-center">
                 
                  <a href="#" class="auth-link text-black">Forgot password?</a>
                </div>
                <!-- <div class="mb-2">
                  <button type="button" class="btn btn-block btn-facebook auth-form-btn">
                    <i class="ti-facebook mr-2"></i>Connect using facebook
                  </button>
                </div>
                <div class="text-center mt-4 font-weight-light">
                  Don't have an account? <a href="register.html" class="text-primary">Create</a>
                </div> -->
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>

</body>

</html>
